import type { Attempt, Category, GradingResult, ScenarioDefinition } from './types'
export const weights: Record<Category, number> = {history:.2,exam:.15,diagnostics:.15,diagnosis:.2,treatment:.2,communication:.1}
const categories: Category[] = ['history','exam','diagnostics','diagnosis','treatment','communication']
export function gradeAttempt(s:ScenarioDefinition,a:Attempt): GradingResult { const scores:Record<Category,number>={history:50,exam:50,diagnostics:50,diagnosis:50,treatment:50,communication:50}; const chosen=new Set(Object.values(a.selectedByPhase).flat()); const feedback:{strengths:string[]; missed:string[]; unnecessary:string[]; unsafe:string[]}= {strengths:[],missed:[],unnecessary:[],unsafe:[]};
 for(const p of s.phases) for(const x of p.actions) if(chosen.has(x.id)) { for(const e of x.effects??[]) scores[e.category]=Math.max(0,Math.min(100,scores[e.category]+e.points)); if(x.effects?.some(e=>e.points>6)) feedback.strengths.push(x.label); if(x.unsafeReason) feedback.unsafe.push(`${x.label}: ${x.unsafeReason}`); if(x.effects?.some(e=>e.points<0)) feedback.unnecessary.push(`${x.label}: ${x.unsafeReason??'This added little value.'}`) }
 for(const d of s.omissions) if(!d.when.some(id=>chosen.has(id))) { for(const e of d.effects) scores[e.category]=Math.max(0,Math.min(100,scores[e.category]+e.points)); feedback.missed.push(d.feedback) }
 const diagnosis=s.diagnoses.find(d=>chosen.has(d.id)); if(diagnosis) for(const e of diagnosis.effects) scores[e.category]=Math.max(0,Math.min(100,scores[e.category]+e.points)); else feedback.missed.push('Select a primary diagnosis before submitting.')
 const critical=s.criticalRules.filter(r=>r.when.some(id=>chosen.has(id))); const plan=s.planOptions.filter(p=>chosen.has(p.id)); for(const p of plan) { for(const e of p.effects) scores[e.category]=Math.max(0,Math.min(100,scores[e.category]+e.points)); if(p.unsafeReason) feedback.unsafe.push(`${p.label}: ${p.unsafeReason}`) }
 const raw=Math.round(categories.reduce((sum,c)=>sum+scores[c]*weights[c],0)); const final=critical.length?Math.min(59,raw):raw; const strengths=feedback.strengths.slice(0,5); if(diagnosis?.id===s.correctPrimary) strengths.push(`Primary diagnosis aligned: ${diagnosis.label}.`); return {categoryScores:scores,rawScore:raw,finalScore:final,passed:!critical.length&&final>=70,criticalSafetyError:critical.length>0,criticalMessages:critical.map(c=>c.explanation),strengths,missed:feedback.missed,unnecessary:feedback.unnecessary,unsafe:feedback.unsafe,diagnosisReasoning:s.diagnoses.find(d=>d.id===s.correctPrimary)?.reasoning??'',idealPlan:s.idealPlan} }
